export linkedin from './icons/linkedin.svg'
export instagram from './icons/insta.svg'
export twitter from './icons/twitter.svg'
export github from './icons/iconmonstr-github.svg'
export globe from './icons/iconmonstr-globe.svg'
export selfie from './selfie.jpg'